language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_8d93bfa0f591_key -iv $encrypted_8d93bfa0f591_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- ls
install:
- npm install
script:
- npm test
deploy:
  provider: gae
  keyfile: client-secret.json
  project: red-ci
